/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cotose;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Francisco
 * @version 1
 */
public class Form extends javax.swing.JFrame {

    /**
     * Variables:
     */
    List<String> descriptions = new ArrayList<>();
    
    public Form() {
        initDescriptions();
        initComponents();
        initListeners();
        initPosition();
    }

    private void initPosition(){
        Dimension screenSize,frameSize;
        int x,y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = this.getSize();
        x = (screenSize.width-frameSize.width)/2;
        y = (screenSize.height-frameSize.height)/2;
        this.setLocation(x, y);
    }
    private void initDescriptions(){
        descriptions.add(Utils.readFileAsLine("descriptionIDE/descripcion_local.txt"));
        descriptions.add(Utils.readFileAsLine("descriptionIDE/descripcion_remote.txt"));
        descriptions.add(Utils.readFileAsLine("descriptionIDE/descripcion_tomcat.txt"));
        descriptions.add(Utils.readFileAsLine("descriptionIDE/descripcion_apache.txt"));
        descriptions.add(Utils.readFileAsLine("descriptionIDE/descripcion_php.txt"));
        descriptions.add(Utils.readFileAsLine("descriptionIDE/descripcion_phpmyadmin.txt"));
        descriptions.add(Utils.readFileAsLine("descriptionIDE/descripcion_sql.txt"));
    }
    private void initListeners(){
        checkLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDescription.setText(descriptions.get(0));
            }
        });
        checkRemote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDescription.setText(descriptions.get(1));
            }
        });
        checkTomcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDescription.setText(descriptions.get(2));
            }
        });
        checkApache.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDescription.setText(descriptions.get(3));
            }
        });
        checkPHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDescription.setText(descriptions.get(4));
            }
        });
        checkPHPmyadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDescription.setText(descriptions.get(5));
            }
        });
        checkSQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDescription.setText(descriptions.get(6));
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonInstall = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        checkLocal = new javax.swing.JCheckBox();
        checkRemote = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkApache = new javax.swing.JCheckBox();
        checkTomcat = new javax.swing.JCheckBox();
        checkPHP = new javax.swing.JCheckBox();
        checkPHPmyadmin = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        checkSQL = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        buttonDynamic = new javax.swing.JButton();
        buttonStatic = new javax.swing.JButton();
        buttonDynSto = new javax.swing.JButton();
        buttonStorage = new javax.swing.JButton();
        labelDescription = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1030, 530));
        jPanel1.setMinimumSize(new java.awt.Dimension(1030, 530));
        jPanel1.setLayout(null);

        buttonInstall.setBackground(new java.awt.Color(255, 255, 255));
        buttonInstall.setForeground(new java.awt.Color(0, 0, 0));
        buttonInstall.setText("Install");
        buttonInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInstallActionPerformed(evt);
            }
        });
        jPanel1.add(buttonInstall);
        buttonInstall.setBounds(820, 470, 170, 50);

        buttonCancel.setBackground(new java.awt.Color(255, 255, 255));
        buttonCancel.setForeground(new java.awt.Color(0, 0, 0));
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel);
        buttonCancel.setBounds(10, 470, 170, 50);

        checkLocal.setBackground(new java.awt.Color(255, 255, 255));
        checkLocal.setForeground(new java.awt.Color(0, 0, 0));
        checkLocal.setText("Local");
        checkLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLocalActionPerformed(evt);
            }
        });
        jPanel1.add(checkLocal);
        checkLocal.setBounds(60, 120, 56, 24);

        checkRemote.setBackground(new java.awt.Color(255, 255, 255));
        checkRemote.setForeground(new java.awt.Color(0, 0, 0));
        checkRemote.setText("Remote");
        checkRemote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRemoteActionPerformed(evt);
            }
        });
        jPanel1.add(checkRemote);
        checkRemote.setBounds(60, 160, 69, 24);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Packages");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 60, 204, 50);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Installation type");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 204, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Web Server");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 120, 102, 33);

        checkApache.setBackground(new java.awt.Color(255, 255, 255));
        checkApache.setForeground(new java.awt.Color(0, 0, 0));
        checkApache.setText("Apache");
        checkApache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkApacheActionPerformed(evt);
            }
        });
        jPanel1.add(checkApache);
        checkApache.setBounds(250, 150, 68, 24);

        checkTomcat.setBackground(new java.awt.Color(255, 255, 255));
        checkTomcat.setForeground(new java.awt.Color(0, 0, 0));
        checkTomcat.setText("Tomcat");
        jPanel1.add(checkTomcat);
        checkTomcat.setBounds(250, 180, 68, 24);

        checkPHP.setBackground(new java.awt.Color(255, 255, 255));
        checkPHP.setForeground(new java.awt.Color(0, 0, 0));
        checkPHP.setText("PHP");
        jPanel1.add(checkPHP);
        checkPHP.setBounds(250, 240, 49, 24);

        checkPHPmyadmin.setBackground(new java.awt.Color(255, 255, 255));
        checkPHPmyadmin.setForeground(new java.awt.Color(0, 0, 0));
        checkPHPmyadmin.setText("PHPmyadmin");
        jPanel1.add(checkPHPmyadmin);
        checkPHPmyadmin.setBounds(250, 330, 101, 24);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Server side");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 210, 102, 33);

        checkSQL.setBackground(new java.awt.Color(255, 255, 255));
        checkSQL.setForeground(new java.awt.Color(0, 0, 0));
        checkSQL.setText("SQL");
        jPanel1.add(checkSQL);
        checkSQL.setBounds(250, 300, 49, 24);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data Base");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 270, 102, 33);

        buttonDynamic.setBackground(new java.awt.Color(255, 255, 255));
        buttonDynamic.setForeground(new java.awt.Color(0, 0, 0));
        buttonDynamic.setText("Dynamic");
        jPanel1.add(buttonDynamic);
        buttonDynamic.setBounds(460, 160, 120, 30);

        buttonStatic.setBackground(new java.awt.Color(255, 255, 255));
        buttonStatic.setForeground(new java.awt.Color(0, 0, 0));
        buttonStatic.setText("Static");
        jPanel1.add(buttonStatic);
        buttonStatic.setBounds(460, 120, 120, 30);

        buttonDynSto.setBackground(new java.awt.Color(255, 255, 255));
        buttonDynSto.setForeground(new java.awt.Color(0, 0, 0));
        buttonDynSto.setText("Dynamic/DB");
        jPanel1.add(buttonDynSto);
        buttonDynSto.setBounds(460, 240, 120, 30);

        buttonStorage.setBackground(new java.awt.Color(255, 255, 255));
        buttonStorage.setForeground(new java.awt.Color(0, 0, 0));
        buttonStorage.setText("Storage");
        jPanel1.add(buttonStorage);
        buttonStorage.setBounds(460, 200, 120, 30);

        labelDescription.setBackground(new java.awt.Color(255, 255, 255));
        labelDescription.setForeground(new java.awt.Color(0, 0, 0));
        labelDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelDescription);
        labelDescription.setBounds(620, 120, 370, 330);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Templates");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 60, 204, 50);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Installation setup");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 10, 510, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkApacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkApacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkApacheActionPerformed

    private void buttonInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInstallActionPerformed
        
        CoToSe.local = checkLocal.isSelected();
        CoToSe.iApache = checkApache.isSelected();
        CoToSe.iTomcat = checkTomcat.isSelected();
        CoToSe.iPHP = checkPHP.isSelected();
        CoToSe.iPHPAdmin = checkPHPmyadmin.isSelected();
        CoToSe.iSQL = checkSQL.isSelected();
        
        CoToSe.point = this.getLocationOnScreen();
        
        CoToSe.installComponents();
        this.setVisible(false);
    }//GEN-LAST:event_buttonInstallActionPerformed

    private void checkLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLocalActionPerformed
        // TODO add your handling code here:
        checkRemote.setSelected(false);
    }//GEN-LAST:event_checkLocalActionPerformed

    private void checkRemoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRemoteActionPerformed
        // TODO add your handling code here:
        checkLocal.setSelected(false);
    }//GEN-LAST:event_checkRemoteActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDynSto;
    private javax.swing.JButton buttonDynamic;
    private javax.swing.JButton buttonInstall;
    private javax.swing.JButton buttonStatic;
    private javax.swing.JButton buttonStorage;
    private javax.swing.JCheckBox checkApache;
    private javax.swing.JCheckBox checkLocal;
    private javax.swing.JCheckBox checkPHP;
    private javax.swing.JCheckBox checkPHPmyadmin;
    private javax.swing.JCheckBox checkRemote;
    private javax.swing.JCheckBox checkSQL;
    private javax.swing.JCheckBox checkTomcat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescription;
    // End of variables declaration//GEN-END:variables
}
