/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cotose;

import java.awt.Point;

/**
 *
 * @author hzone
 */
public class Form2 extends javax.swing.JFrame {

    /**
     * Creates new form Form2
     */
    
    public Form2() {
        initComponents();
        this.setLocation(CoToSe.point);
    }

    public void setStep(String str){
        labelInstall.setText(str);
    }
    public void setValue(int v){
        labelValue.setText(String.valueOf(v));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barInstall = new javax.swing.JProgressBar();
        labelValue = new javax.swing.JLabel();
        labelInstall = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 531));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Installation process");
        jLabel1.setMaximumSize(new java.awt.Dimension(97, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(97, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(97, 16));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 12, 510, 50);

        barInstall.setForeground(new java.awt.Color(153, 255, 153));
        barInstall.setToolTipText("");
        barInstall.setValue(80);
        jPanel1.add(barInstall);
        barInstall.setBounds(70, 150, 850, 30);

        labelValue.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        labelValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValue.setText("0");
        labelValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(labelValue);
        labelValue.setBounds(830, 120, 60, 30);

        labelInstall.setFont(new java.awt.Font("Microsoft JhengHei Light", 2, 12)); // NOI18N
        labelInstall.setText("Line being installed/executed");
        jPanel1.add(labelInstall);
        labelInstall.setBounds(70, 200, 850, 30);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel4.setText("%");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(900, 120, 40, 30);

        buttonFinish.setBackground(new java.awt.Color(255, 255, 255));
        buttonFinish.setText("Finish");
        jPanel1.add(buttonFinish);
        buttonFinish.setBounds(851, 486, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barInstall;
    private javax.swing.JButton buttonFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInstall;
    private javax.swing.JLabel labelValue;
    // End of variables declaration//GEN-END:variables
}
